PetalburgCity_Gym_Text_GiveEnigmaBerry:
	.string "PAPA: Bonjour, {PLAYER}!\p"
	.string "Je viens de recevoir une baie très rare.\n"
	.string "J’aimerais te la donner.$"

Route104_Text_PlantBerriesInSoilTakeThis:
	.string "Si tu vois des baies qui ont poussé\n"
	.string "sur une terre meuble et fertile,\l"
	.string "tu peux les prendre.\p"
	.string "Mais tu dois semer une autre baie à cet\n"
	.string "endroit. C’est la moindre des choses.\p"
	.string "Tiens, je vais partager ça avec toi.$"

Route104_Text_TrainersOftenMakeMonHoldBerries:
	.string "A te voir, tu dois être dresseur,\n"
	.string "n’est-ce pas?\p"
	.string "Les dresseurs font souvent tenir\n"
	.string "des baies à leurs Pokémon.\p"
	.string "A toi de voir si tu préfères faire\n"
	.string "pousser des baies ou les utiliser!$"

Route111_Text_WateredPlantsEveryDayTakeBerry:
	.string "J’ai arrosé les plantes chaque jour.\n"
	.string "Elles ont donné beaucoup de fleurs.\p"
	.string "Et elles m’ont aussi procuré de\n"
	.string "nombreuses baies.\p"
	.string "Vas-y!\n"
	.string "Prends!$"

Route111_Text_GoingToTryToMakeDifferentColorBerries:
	.string "Je vais tout faire pour essayer\n"
	.string "d’obtenir des {PokéBlock}s de différentes\l"
	.string "couleurs!\p"
	.string "J’espère que tu vas tout faire aussi!$"

Route111_Text_WhatColorBerriesToLookForToday:
	.string "Je vais chercher des baies de quelle\n"
	.string "couleur aujourd’hui?$"

Route114_Text_LoveUsingBerryCrushShareBerry:
	.string "J’adore utiliser le BROYEUR DE baies,\n"
	.string "alors je ramasse plein de baies!\p"
	.string "Je suis d’accord pour t’en donner\n"
	.string "une si tu veux!$"

Route114_Text_TryBerryCrushWithFriends:
	.string "Tu devrais essayer le BROYEUR DE\n"
	.string "baies avec tes amis.$"

Route114_Text_FunToThinkAboutBerries:
	.string "Quelles sortes de baies vais-je\n"
	.string "planter? Et faut-il les utiliser ou\l"
	.string "les conserver?\p"
	.string "Se préoccuper de petites choses de ce\n"
	.string "genre a aussi son charme.$"

Route120_Text_BerriesExpressionOfLoveIsntIt:
	.string "Les baies poussent en profitant de\n"
	.string "la lumière du soleil.\p"
	.string "Nous les aidons à pousser en les\n"
	.string "arrosant régulièrement.\p"
	.string "C’est une marque d’attention,\n"
	.string "n’est-ce pas?$"

Route120_Text_YesYouUnderstand:
	.string "Oui, oui.\n"
	.string "Tu vois ce que je veux dire.\p"
	.string "Tu devrais prendre ça.$"

Route120_Text_MakeYourOwnImpressions:
	.string "Oh… Mais je suppose qu’il est important\n"
	.string "que tu te fasses ta propre opinion…\p"
	.string "Tu n’as qu’à prendre ça.$"

Route120_Text_BerryIsRareRaiseItWithCare:
	.string "Cette baie me semble rare. J’espère\n"
	.string "que tu vas en prendre bien soin.$"

Route120_Text_IllGetMoreBerriesFromBerryMaster:
	.string "Je vais aller chercher d’autres baies\n"
	.string "chez le Maître des Baies.$"

LilycoveCity_Text_BerrySuitsYou:
	.string "Quand on y regarde de près…\p"
	.string "les costumes me conviennent\n"
	.string "parfaitement.\p"
	.string "Et toi, une baie, ça te convient…\p"
	.string "Et pourquoi donc?$"

LilycoveCity_Text_BecauseYoureTrainer:
	.string "Si on veut trouver une explication…\p"
	.string "c’est parce que tu es dresseur!$"

LilycoveCity_Text_PokeblocksSuitPokemon:
	.string "Quand on y regarde de près…\p"
	.string "tout comme la simplicité me va, les\n"
	.string "{PokéBlock}s conviennent très bien aux\l"
	.string "Pokémon.$"

Route123_BerryMastersHouse_Text_YoureDeservingOfBerry:
	.string "Tu peux m’appeler le Maître des Baies.\p"
	.string "Je rêve de recouvrir le monde de fleurs\n"
	.string "magnifiques, alors je fais pousser des\l"
	.string "baies et j’en donne à tout le monde.\p"
	.string "Je te donne celle qui te revient!$"

Route123_BerryMastersHouse_Text_WhyBeStingyTakeAnother:
	.string "Pourquoi être radin?\n"
	.string "Prends-en une autre!$"

Route123_BerryMastersHouse_Text_VisitPrettyPetalFlowerShop:
	.string "N’oublie pas d’aller chez le Fleuriste\n"
	.string "Jolie Fleur, près de Mérouville.\p"
	.string "Que les fleurs recouvrent la planète!$"

Route123_BerryMastersHouse_Text_DoneForToday:
	.string "J’ai fini pour aujourd’hui.\n"
	.string "Repasse un autre jour.\p"
	.string "Que les fleurs recouvrent la planète!$"

Route123_BerryMastersHouse_Text_HeardAGoodSayingLately:
	.string "Pour faire pousser des baies, mon mari,\n"
	.string "c’est le meilleur.\p"
	.string "Je suis fière de lui, vraiment.\p"
	.string "Au fait, mon p’tit, t’aurais pas entendu\n"
	.string "une belle expression récemment?$"

Route123_BerryMastersHouse_Text_InspirationalTakeThis:
	.string "Ah! Quelle expression remarquable!\n"
	.string "Ça, c’est de l’inspiration!\p"
	.string "Je veux que tu prennes ça.$"

Route123_BerryMastersHouse_Text_GoodSayingTakeThis:
	.string "Oh! Quelle belle expression!\n"
	.string "Tu es remarquable.\p"
	.string "J’aimerais que tu prennes ça.$"

Route123_BerryMastersHouse_Text_JoyNeverGoesOutOfMyLife:
	.string "Nos quatre petits-enfants devraient\n"
	.string "être encore meilleurs que mon mari.\p"
	.string "J’ai toujours eu une vie heureuse!$"

Route123_BerryMastersHouse_Text_Ah:
	.string "Ah…$"

Route104_PrettyPetalFlowerShop_Text_ThisIsPrettyPetalFlowerShop:
	.string "Bonjour!\p"
	.string "Voici le Fleuriste Jolie Fleur.\n"
	.string "Vive les fleurs, plantons-en partout!$"

Route104_PrettyPetalFlowerShop_Text_LearnAboutBerries:
	.string "{PLAYER}{KUN}, voulez-vous en savoir plus\n"
	.string "sur les baies?$"

Route104_PrettyPetalFlowerShop_Text_IntroLearnAboutBerries:
	.string "Comment vous appelez-vous?\p"
	.string "{PLAYER}{KUN}.\n"
	.string "Quel joli nom!\p"
	.string "{PLAYER}{KUN}, voulez-vous en savoir plus\n"
	.string "sur les baies?$"

Route104_PrettyPetalFlowerShop_Text_BerriesExplanation:
	.string "Les baies proviennent d’arbres\n"
	.string "poussant sur un sol meuble et fertile.\p"
	.string "Quand on cueille une baie, il faut\n"
	.string "en replanter une au même endroit.\p"
	.string "La baie plantée poussera rapidement\n"
	.string "pour devenir une plante, fleurir, et\l"
	.string "donner à son tour des baies.\p"
	.string "J’aimerais que le monde entier soit\n"
	.string "recouvert de fleurs magnifiques.\l"
	.string "C’est mon rêve le plus cher.\p"
	.string "Vous pouvez m’aider, {PLAYER}{KUN}, en\n"
	.string "plantant des baies un peu partout.$"

Route104_PrettyPetalFlowerShop_Text_FlowersBringHappiness:
	.string "Les fleurs illuminent la vie des gens,\n"
	.string "n’est-ce pas?$"

Route104_PrettyPetalFlowerShop_Text_YouCanHaveThis:
	.string "Bonjour!\p"
	.string "Pour que les fleurs soient belles,\n"
	.string "il faut bien s’en occuper.\p"
	.string "Vous allez aimer soigner vos fleurs, j’en\n"
	.string "suis sûre. Tenez, c’est pour vous.$"

Route104_PrettyPetalFlowerShop_Text_WailmerPailExplanation:
	.string "Pour faire pousser les plantes\n"
	.string "à baies, il faut les arroser avec\l"
	.string "le seau Wailmer.\p"
	.string "Ah, autre chose.\p"
	.string "Si on ne cueille pas de baies pendant\n"
	.string "un petit moment, elles tombent par\l"
	.string "terre. Mais d’autres repoussent vite.\p"
	.string "C’est étrange, non? Comme si elles\n"
	.string "avaient le désir de vivre.$"

Route104_PrettyPetalFlowerShop_Text_ImGrowingFlowers:
	.string "J’essaie d’imiter mes grandes sœurs.\n"
	.string "Alors je fais aussi pousser des fleurs!\p"
	.string "Tiens! C’est pour toi!$"

Route104_PrettyPetalFlowerShop_Text_MachineMixesBerries:
	.string "Les baies, tu peux les planter ou les\n"
	.string "donner à porter à des Pokémon.\p"
	.string "Maintenant, il existe aussi une machine\n"
	.string "qui sert à mixer les baies pour faire\l"
	.string "des bonbons pour Pokémon.\p"
	.string "Je veux des bonbons aussi.$"

SootopolisCity_Text_NameIsKiriHaveOneOfThese:
	.string "Salut, comment tu t’appelles?\p"
	.string "… … …  … … … … … …\n"
	.string "C’est un beau nom!\p"
	.string "Moi c’est Joy.\p"
	.string "Mon papa et ma maman m’ont appelée\n"
	.string "comme ça pour que je sois tout le temps\l"
	.string "joyeuse.\p"
	.string "C’est ce qu’ils voulaient.\n"
	.string "Tiens, prends-en une.$"

SootopolisCity_Text_GiveYouThisBerryToo:
	.string "Je vais aussi te donner cette baie,\n"
	.string "la baie préférée de Joy!$"

SootopolisCity_Text_WhatKindOfWishInYourName:
	.string "Et toi, je me demande pourquoi\n"
	.string "tu t’appelles comme ça.$"

SootopolisCity_Text_LikeSeasonBornIn:
	.string "Printemps, été, automne et hiver.\p"
	.string "En naissant au printemps, on aime le\n"
	.string "printemps? Et en naissant en été, on\l"
	.string "aime l’été?$"

SootopolisCity_Text_ThenILoveAutumn:
	.string "Joy est née en automne,\n"
	.string "alors j’adore l’automne!\p"
	.string "Et toi, quelle est ta saison préférée?$"

SootopolisCity_Text_OhDoesntMatter:
	.string "Oh…\n"
	.string "C’est pas grave…\p"
	.string "J’aimerais savoir tellement de choses…$"
