gText_ObtainedTheItem::
    .string "Obtenu: {STR_VAR_2}!$"

gText_TheBagIsFull::
    .string "Le Sac est plein…$"

gText_PutItemInPocket::
    .string "{PLAYER} met {STR_VAR_2} dans\n"
    .string "Poche {STR_VAR_3}.$"

gText_PlayerFoundOneItem::
    .string "{PLAYER} trouve {STR_VAR_2}!$"

gText_TooBadBagIsFull::
    .string "Dommage!\n"
    .string "Le Sac est plein.$"

gText_PlayerPutItemInBag::
    .string "{PLAYER} met {STR_VAR_2} dans\n"
    .string "le Sac.$"

gText_ObtainedTheDecor::
    .string "Obtenu: {STR_VAR_2}!$"

gText_NoRoomLeftForAnother::
    .string "Dommage! Il n’y a plus assez de place\n"
    .string "pour {STR_VAR_2}…$"

gText_TheDecorWasTransferredToThePC::
    .string "Transfert de {STR_VAR_2} sur le PC.$"
