gText_PkmnTransferredSomeonesPC::
    .string "{STR_VAR_2} a été transféré sur le\n"
    .string "PC de ???.\p"
    .string "Il a été placé dans la boîte\n"
    .string "appelée “{STR_VAR_1}”.$"

gText_PkmnTransferredLanettesPC::
    .string "{STR_VAR_2} a été transféré sur le\n"
    .string "PC d’Annette.\p"
    .string "Il a été placé dans la boîte\n"
    .string "appelée “{STR_VAR_1}”.$"

gText_PkmnTransferredSomeonesPCBoxFull::
    .string "La boîte {STR_VAR_3} sur le PC\n"
    .string "de ??? est pleine.\p"
    .string "{STR_VAR_2} a été placé dans la\n"
    .string "boîte appelée “{STR_VAR_1}”.$"

gText_PkmnTransferredLanettesPCBoxFull::
    .string "La boîte “{STR_VAR_3}” sur le PC\n"
    .string "d’Annette est pleine.\p"
    .string "{STR_VAR_2} a été placé dans la\n"
    .string "boîte appelée “{STR_VAR_1}”.$"

gText_NoMoreRoomForPokemon::
    .string "Il n’y a plus de place pour\n"
    .string "les POKéMON.\p"
    .string "Les boîtes sont pleines et\n"
    .string "ne peuvent plus rien recevoir.$"

gText_NicknameThisPokemon::
    .string "Voulez-vous donner un surnom\n"
    .string "à {STR_VAR_1}?$"
